name: Switch Traffic (Zero Downtime)

on:
  repository_dispatch:
    types: 
      - switch-to-green
      - switch-to-blue

jobs:
  switch-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Switch Traffic to GREEN
        if: github.event.action == 'switch-to-green'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_GATEWAY_HOST }}
          username: ${{ secrets.EC2_GATEWAY_USERNAME }}
          key: ${{ secrets.EC2_GATEWAY_SSH_KEY }}
          script: |
            curl -X POST http://localhost:9090/actuator/gateway/routes/bidmart-auction \
              -H "Content-Type: application/json" \
              -d '{"uri": "http://${{ secrets.IP_EC2_GREEN }}:8083", "predicates": [{"name": "Path", "args": {"pattern": "/api/auctions/**"}}], "filters": [{"name": "RequestRateLimiter", "args": {"redis-rate-limiter.replenishRate": "20", "redis-rate-limiter.burstCapacity": "40", "key-resolver": "#{@ipKeyResolver}"}}, {"name": "JwtAuthenticationFilter"}]}'
            curl -X POST http://localhost:9090/actuator/gateway/refresh

      - name: Switch Traffic to BLUE
        if: github.event.action == 'switch-to-blue'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_GATEWAY_HOST }}
          username: ${{ secrets.EC2_GATEWAY_USERNAME }}
          key: ${{ secrets.EC2_GATEWAY_SSH_KEY }}
          script: |
            curl -X POST http://localhost:9090/actuator/gateway/routes/bidmart-auction \
              -H "Content-Type: application/json" \
              -d '{"uri": "http://${{ secrets.IP_EC2_BLUE }}:8083", "predicates": [{"name": "Path", "args": {"pattern": "/api/auctions/**"}}], "filters": [{"name": "RequestRateLimiter", "args": {"redis-rate-limiter.replenishRate": "20", "redis-rate-limiter.burstCapacity": "40", "key-resolver": "#{@ipKeyResolver}"}}, {"name": "JwtAuthenticationFilter"}]}'
            curl -X POST http://localhost:9090/actuator/gateway/refresh
