name: Switch Traffic (Zero Downtime)

on:
  repository_dispatch:
    types: 
      - switch-to-green
      - switch-to-blue
  workflow_dispatch:
    inputs:
      target:
        description: 'Target Deployment (switch-to-blue / switch-to-green)'
        required: true
        default: 'switch-to-green'
        type: choice
        options:
          - switch-to-green
          - switch-to-blue

jobs:
  switch-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Switch Traffic to GREEN
        if: github.event.action == 'switch-to-green' || github.event.inputs.target == 'switch-to-green'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_GATEWAY_HOST }}
          username: ${{ secrets.EC2_GATEWAY_USERNAME }}
          key: ${{ secrets.EC2_GATEWAY_SSH_KEY }}
          script: |
            echo "Waiting for Gateway to be healthy..."
            for i in {1..10}; do docker exec bidmart-gateway curl -s http://127.0.0.1:9090/actuator/health && break || sleep 3; done
            
            echo "Switching traffic to GREEN..."
            docker exec bidmart-gateway curl -v --retry 5 --retry-connrefused --retry-delay 5 -X POST http://127.0.0.1:9090/actuator/gateway/routes/bidmart-auction \
              -H "Content-Type: application/json" \
              -d '{"uri": "${{ secrets.AUCTION_SERVICE_URL_GREEN }}", "predicates": [{"name": "Path", "args": {"_genkey_0": "/api/auctions/**"}}], "filters": [{"name": "JwtAuthenticationFilter"}]}'
            docker exec bidmart-gateway curl -v --retry 5 --retry-connrefused --retry-delay 5 -X POST http://127.0.0.1:9090/actuator/gateway/refresh

      - name: Switch Traffic to BLUE
        if: github.event.action == 'switch-to-blue' || github.event.inputs.target == 'switch-to-blue'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_GATEWAY_HOST }}
          username: ${{ secrets.EC2_GATEWAY_USERNAME }}
          key: ${{ secrets.EC2_GATEWAY_SSH_KEY }}
          script: |
            echo "Waiting for Gateway to be healthy..."
            for i in {1..10}; do docker exec bidmart-gateway curl -s http://127.0.0.1:9090/actuator/health && break || sleep 3; done

            echo "Switching traffic to BLUE..."
            docker exec bidmart-gateway curl -v --retry 5 --retry-connrefused --retry-delay 5 -X POST http://127.0.0.1:9090/actuator/gateway/routes/bidmart-auction \
              -H "Content-Type: application/json" \
              -d '{"uri": "${{ secrets.AUCTION_SERVICE_URL_BLUE }}", "predicates": [{"name": "Path", "args": {"_genkey_0": "/api/auctions/**"}}], "filters": [{"name": "JwtAuthenticationFilter"}]}'
            docker exec bidmart-gateway curl -v --retry 5 --retry-connrefused --retry-delay 5 -X POST http://127.0.0.1:9090/actuator/gateway/refresh
